BikeSharing/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('a0_landing_page.urls')),
    path('admin/', admin.site.urls),

    # A1
    path('login', include('a1_login.urls')),
    path('register', include('a1_register.urls')),
    path('topup', include('a1_top_up.urls')),

    # A2
    path('tasks/', include('a2_cud_tasks.urls')),
    path('events/', include('a2_cud_events.urls')),

    # A3
    path('bikes/', include('a3_view_bikes.urls')),
    path('stations/', include('a3_view_stations.urls')),

    # A4
    path('voucher/', include('a4_cud_vouchers.urls')),
    path('rents/', include('a4_cu_rents.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

a1_login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
]

a2_cud_events/urls.py
from django.urls import path

from . import views

app_name = 'event'
urlpatterns = [
    path('', views.index, name='events-index'),
    path('create/', views.create, name='create'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete')
]

a2_cud_events/models.py
from django.db import models

# Create your models here.

a2_cud_events/views.py
import json
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from BikeSharing.database import select_query, insert_update_delete_query

def index(request):
    list_events = select_query("""
        SELECT *
        FROM ACARA;
    """)

    list_events = [{"id_event": v[0],
                    "judul": v[1],
                    "deskripsi": v[2],
                    "gratis": v[5],
                    "tanggal_mulai": v[3],
                    "tanggal_selesai": v[4]}
                    for v in list_events]
    
    events = {
        "events" : list_events,
        "account_name": request.COOKIES.get('username'),
        "role" : request.COOKIES.get('role')
    }

    return render(request, 'index-events.html', events)

@csrf_exempt
def create(request):
    data ={}
    if(request.method == 'GET'):
        list_stasiun = select_query("""
            SELECT *
            FROM STASIUN;
            """)

        list_stasiun = [{"id_stasiun": v[0],
                        "nama": v[4]}
                        for v in list_stasiun]

        data = {
            "event" : {
                "id_event":"1",
                "judul" : "Judul",
                "deskripsi":"Deskripsi",
                "gratis":"Ya/Tidak",
                "tanggal_mulai" : "Tanggal Mulai",
                "tanggal_selesai" : "Tanggal Selesai",
                "stasiun" : "Stasiun"
            },
            "account_name": request.COOKIES.get('username'),
            "role" : request.COOKIES.get('role'),
            "stasiun" : list_stasiun
        }

    elif(request.method == 'POST'):
        # TODO: implement query
        max_id = select_query("""
            SELECT MAX(CAST(id_acara AS DECIMAL))
            FROM ACARA;
            """)

        id = int(max_id[0][0]) + 1
        judul = request.POST.get("judul")
        deskripsi = request.POST.get("deskripsi")
        gratis = request.POST.get("gratis")
        tanggal_mulai = request.POST.get("tanggal_mulai")
        tanggal_selesai = request.POST.get("tanggal_selesai")
        stasiun = request.POST.getlist("stasiun")

        rows_insert_to_acara = insert_update_delete_query("""
            INSERT INTO ACARA
            VALUES ('%s', '%s', '%s', '%s', '%s', '%s');
            """ % (id, judul, deskripsi, tanggal_mulai, tanggal_selesai, gratis))

        for st_idx in stasiun:
            rows_insert_to_acara_stasiun = insert_update_delete_query("""
                INSERT INTO ACARA_STASIUN
                VALUES ('%s', '%s');
                """ % (st_idx, id))
        return redirect('/events/')
    return render(request, 'create-events.html', data)

@csrf_exempt
def update(request, id):
    data ={}
    if(request.method == 'GET'):
        curr_event = select_query("""
            SELECT *
            FROM ACARA
            WHERE id_acara = '%s';
            """ % (id))

        curr_event = [{"id_event": v[0],
                    "judul": v[1],
                    "deskripsi": v[2],
                    "gratis": v[5],
                    "tanggal_mulai": v[3],
                    "tanggal_selesai": v[4]}
                    for v in curr_event]

        list_stasiun = select_query("""
            SELECT *
            FROM STASIUN;
            """)

        list_stasiun_selected = select_query("""
            SELECT s.id_stasiun, s.nama
            FROM ACARA_STASIUN ast, STASIUN s
            WHERE ast.id_acara = '%s' AND ast.id_stasiun = s.id_stasiun;
            """ % (id))

        new_list_stasiun = []

        for a in list_stasiun:
            flag = False
            for b in list_stasiun_selected:
                if(a[0] == b[0]):
                    flag = True
            if(flag):
                new_list_stasiun.append({"id_stasiun" : a[0], "nama" : a[4], "selected" : True})
            else:
                new_list_stasiun.append({"id_stasiun" : a[0], "nama" : a[4], "selected" : False})

        data = {
            "event" : curr_event[0],
            "account_name": request.COOKIES.get('username'),
            "role" : request.COOKIES.get('role'),
            "stasiun" : new_list_stasiun
        }

    elif(request.method == 'POST'):
        # TODO: implement query
        judul = request.POST.get("judul")
        deskripsi = request.POST.get("deskripsi")
        gratis = request.POST.get("gratis")
        tanggal_mulai = request.POST.get("tanggal_mulai")
        tanggal_selesai = request.POST.get("tanggal_selesai")
        stasiun = request.POST.getlist("stasiun")

        rows_updated_to_acara = insert_update_delete_query("""
            UPDATE ACARA
            SET judul = '%s', deskripsi = '%s', is_free = '%s', tgl_mulai = '%s', tgl_akhir = '%s'
            WHERE id_acara = '%s';
            """ % (judul, deskripsi, gratis, tanggal_mulai, tanggal_selesai, id))

        rows_deleted_to_acara_stasiun = insert_update_delete_query("""
                DELETE FROM ACARA_STASIUN
                WHERE id_acara = '%s';
                """ % (id))
        
        for st_idx in stasiun:
            rows_insert_to_acara_stasiun = insert_update_delete_query("""
                INSERT INTO ACARA_STASIUN
                VALUES ('%s', '%s');
                """ % (st_idx, id))
            
        return redirect('/events/')
    return render(request, 'update-events.html', data)

@csrf_exempt
def delete(request, id):
    rows_deleted_to_acara_stasiun = insert_update_delete_query("""
        DELETE FROM ACARA_STASIUN
        WHERE id_acara = '%s';
        """ % (id))
    rows_deleted_to_acara = insert_update_delete_query("""
        DELETE FROM ACARA
        WHERE id_acara = '%s';
        """ % (id))
    return redirect('/events/')

a2_cud_events/templates/create-events.html
{% extends "html_base.html" %}
{% load staticfiles %}


{% block title %}ShareBike{% endblock %}


{% block local_static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}


{% block body %}
    {% if role == "admin" %}
        <div class="container">
                <form action="{% url 'event:create' %}" method="POST">
                    <div class="form-group">
                        <label for="judul"><b>Judul</b></label>
                        <input type="text" name="judul" class="form-control" id="judul" placeholder="{{ event.judul }}" required>
                    </div>
                    <div class="form-group">
                        <label for="deskripsi"><b>Deskripsi</b></label>
                        <input type="text" name="deskripsi" class="form-control" id="deskripsi" placeholder="{{ event.deskripsi }}" required>
                    </div>
                    <div class="form-group">
                        <label for="gratis"><b>Gratis</b></label>
                        <select class="form-control" id="gratis" name="gratis" required>
                            <option value="True">Ya</option>
                            <option value="False">Tidak</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="tanggal_mulai"><b>Tanggal Mulai</b></label>
                        <input type="date" name="tanggal_mulai" class="form-control" id="tanggal_mulai" required>
                    </div>
                    <div class="form-group">
                        <label for="tanggal_selesai"><b>Tanggal Selesai</b></label>
                        <input type="date" name="tanggal_selesai" class="form-control" id="tanggal_selesai" required>
                    </div>
                    <div class="form-group">
                        <label for="stasiun"><b>Stasiun</b> <i>(hold CTRL or CMD to select multiple)</i></label><br>
                        <select class="form-control" id="stasiun" name="stasiun" size="10" multiple required>
                            {% for s in stasiun %}
                            <option value="{{ s.id_stasiun }}">{{ s.nama }}</option>
                            {% endfor %}
                          </select>
                    </div>
                    <button type="submit" class="btn btn-success">Create events!</button>
                </form>
        </div>
    {% endif %}

    {% if role == "anggota" or role == "petugas" %}
        <div>You are not Authorized to access this page.</div>
    {% endif %}
	<footer class="container-fluid text-center">
		<p>2019, ShareBike team.</p> 
	</footer>
{% endblock %}

a2_cud_events/templates/index-events.html
{% extends "html_base.html" %}
{% load staticfiles %}


{% block title %}ShareBike{% endblock %}


{% block local_static %}
 <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}


{% block body %}
 <div class="container">
  {% if role == "admin" %}
   <div clas="row">
    <a href="{% url 'event:create' %}"><button type="button" class="btn btn-success">Create event</button></a>
   </div>
  {% endif %}
  <div class="row">
    <table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
       <tr>
        <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="id
        : activate to sort column ascending">No
        </th>
        <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="judul
        : activate to sort column ascending">Judul
        </th>
        <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="deskripsi
        : activate to sort column ascending">Deskripsi
        </th>
        <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="gratis
        : activate to sort column ascending">Is Free
        </th>
        <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="tanggal_mulai
        : activate to sort column ascending">Tanggal Mulai
        </th>
        <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="tanggal_selesai
        : activate to sort column ascending">Tanggal Akhir
        </th>
        {% if role == "admin" %}
        <th class="th-sm">ACTION
        </th>
        {% endif %}
       </tr>
      </thead>
      <tbody>
     {% for event in events %}
     <tr>
      <td>{{ event.id_event }}</td>
      <td>{{ event.judul }}</td>
      <td>{{ event.deskripsi }}</td>
      {% if event.gratis %}
      <td>Ya</td>
      {% else %}
      <td>Tidak</td>
      {% endif %}
      <td>{{ event.tanggal_mulai|date:"j F Y" }}</td>
      <td>{{ event.tanggal_selesai|date:"j F Y" }}</td>
      {% if role == "admin" %}
       <td>
         <a href="{% url 'event:update' event.id_event %}"><button type="button" class="btn btn-primary">Update</button></a>
         <a href="{% url 'event:delete' event.id_event %}"><button type="button" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?');">Delete</button></a>
      </td>
      {% endif %}
       </tr>
    {% endfor %}
   </tbody>
  </table>
 </div>
</div>
</div>

 <footer class="container-fluid text-center">
  <p>2019, ShareBike team.</p> 
 </footer>
 <script>
   $(document).ready(function() {
    $('#dtBasicExample').DataTable();
    });
 </script>
{% endblock %}

a2_cud_events/templates/update-events.html
{% extends "html_base.html" %}
{% load staticfiles %}


{% block title %}ShareBike{% endblock %}


{% block local_static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}


{% block body %}
    {% if role == "admin" %}
        <div class="container">
            <form action="{% url 'event:update' event.id_event %}" method="POST">
                <div class="form-group">
                        <label for="judul"><b>Judul</b></label>
                        <input type="text" name="judul" class="form-control" id="judul" placeholder="Judul" value="{{ event.judul }}" required>
                    </div>
                    <div class="form-group">
                        <label for="deskripsi"><b>Deskripsi</b></label>
                        <input type="text" name="deskripsi" class="form-control" id="deskripsi" placeholder="Deskripsi" value="{{ event.deskripsi }}" required>
                    </div>
                    <div class="form-group">
                        <label for="gratis"><b>Gratis</b></label>
                        <select class="form-control" id="gratis" name="gratis" required>
                            {% if event.gratis %}
                            <option value="True" selected="selected">Ya</option>
                            <option value="False">Tidak</option>
                            {% else %}
                            <option value="True">Ya</option>
                            <option value="False" selected="selected">Tidak</option>
                            {% endif %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="tanggal_mulai"><b>Tanggal Mulai</b></label>
                        <input type="date" name="tanggal_mulai" class="form-control" id="tanggal_mulai" value="{{ event.tanggal_mulai|date:'Y-m-d' }}" required>
                    </div>
                    <div class="form-group">
                        <label for="tanggal_selesai"><b>Tanggal Selesai</b></label>
                        <input type="date" name="tanggal_selesai" class="form-control" id="tanggal_selesai" value="{{ event.tanggal_selesai|date:'Y-m-d' }}" required>
                    </div>
                    <div class="form-group">
                        <label for="stasiun"><b>Stasiun</b> <i>(hold CTRL or CMD to select multiple)</i></label><br>
                        <select class="form-control" id="stasiun" name="stasiun" size="10" multiple required>
                            {% for s in stasiun %}
                                {% if s.selected %}
                                <option value="{{ s.id_stasiun }}" selected>{{ s.nama }}</option>
                                {% else %}
                                <option value="{{ s.id_stasiun }}">{{ s.nama }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    {% endif %}

    {% if role == "anggota" or role == "petugas" %}
        <div>You are not Authorized to access this page.</div>
    {% endif %}
	<footer class="container-fluid text-center">
		<p>2019, ShareBike team.</p> 
	</footer>
{% endblock %}