BikeSharing/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('a0_landing_page.urls')),
    path('admin/', admin.site.urls),

    # A1
    path('login', include('a1_login.urls')),
    path('register', include('a1_register.urls')),
    path('topup', include('a1_top_up.urls')),

    # A2
    path('tasks/', include('a2_cud_tasks.urls')),
    path('events/', include('a2_cud_events.urls')),

    # A3
    path('bikes/', include('a3_view_bikes.urls')),
    path('stations/', include('a3_view_stations.urls')),

    # A4
    path('voucher/', include('a4_cud_vouchers.urls')),
    path('rents/', include('a4_cu_rents.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

a1_login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
]

a2_cud_tasks/urls.py
from django.urls import path

from . import views

app_name = 'task'
urlpatterns = [
    path('', views.index, name='tasks-index'),
    path('create/', views.create, name='create'),
    path('update/<str:ktp>/<str:tgl_mulai>/<str:id_stasiun>', views.update, name='update'),
    path('delete/<str:ktp>/<str:tgl_mulai>/<str:id_stasiun>', views.delete, name='delete')
]

a2_cud_tasks/models.py
from django.db import models

# Create your models here.

a2_cud_tasks/views.py
import json
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from BikeSharing.database import select_query, insert_update_delete_query

def index(request):
    list_tasks = select_query("""
        SELECT pn.ktp, ps.nama as nama_petugas, pn.start_datetime, pn.end_datetime, pn.id_stasiun, st.nama as nama_stasiun
        FROM penugasan pn, person ps, petugas pt, stasiun st
        WHERE pn.ktp = pt.ktp AND pt.ktp = ps.ktp AND st.id_stasiun = pn.id_stasiun;
    """)

    list_tasks = [{"id_task": v + 1,
                    "no_ktp": list_tasks[v][0],
                    "nama_petugas": list_tasks[v][1],
                    "tanggal_mulai": list_tasks[v][2],
                    "tanggal_selesai": list_tasks[v][3],
                    "id_stasiun": list_tasks[v][4],
                    "nama_stasiun": list_tasks[v][5]}
                    for v in range(len(list_tasks))]

    tasks = {
        "tasks" : list_tasks,
        "account_name": request.COOKIES.get('username'),
        "role" : request.COOKIES.get('role')
    }
    return render(request, 'index-tasks.html', tasks)

@csrf_exempt
def create(request):
    data ={}
    if(request.method == 'GET'):
        list_stasiun = select_query("""
            SELECT *
            FROM STASIUN;
            """)

        list_stasiun = [{"id_stasiun": v[0],
                        "nama": v[4]}
                        for v in list_stasiun]

        list_petugas = select_query("""
            SELECT pt.ktp, ps.nama
            FROM PETUGAS pt, PERSON ps
            WHERE pt.ktp = ps.ktp;
            """)

        list_petugas = [{"no_ktp": v[0],
                        "nama_petugas": v[1]}
                        for v in list_petugas]
        
        data = {
            "task" : {
                "id_task":"1",
                "petugas" : "Petugas",
                "tanggal_mulai" : "Tanggal Mulai",
                "tanggal_selesai" : "Tanggal Selesai",
                "stasiun" : "Stasiun"
            },
            "account_name": request.COOKIES.get('username'),
            "role" : request.COOKIES.get('role'),
            "stasiun" : list_stasiun,
            "petugas" : list_petugas
        }
    elif(request.method == 'POST'):
        # TODO: implement query
        no_ktp = request.POST.get("petugas")
        tanggal_mulai = request.POST.get("tanggal_mulai")
        tanggal_selesai = request.POST.get("tanggal_selesai")
        stasiun = request.POST.get("stasiun")

        rows_insert_to_acara = insert_update_delete_query("""
            INSERT INTO PENUGASAN
            VALUES ('%s', '%s', '%s', '%s');
            """ % (no_ktp, tanggal_mulai, stasiun, tanggal_selesai))
        return redirect('/tasks/')
    return render(request, 'create-tasks.html', data)

@csrf_exempt
def update(request, ktp, tgl_mulai, id_stasiun):
    data ={}
    if(request.method == 'GET'):
        curr_task = select_query("""
            SELECT pn.ktp, ps.nama as nama_petugas, pn.start_datetime, pn.end_datetime, pn.id_stasiun, st.nama as nama_stasiun
            FROM penugasan pn, person ps, petugas pt, stasiun st
            WHERE pn.ktp = pt.ktp AND pt.ktp = ps.ktp AND st.id_stasiun = pn.id_stasiun AND pn.ktp = '%s' AND pn.start_datetime = '%s' AND pn.id_stasiun = '%s';
            """ % (ktp, tgl_mulai, id_stasiun))

        curr_task = [{"no_ktp": curr_task[v][0],
                    "nama_petugas": curr_task[v][1],
                    "tanggal_mulai": curr_task[v][2],
                    "tanggal_selesai": curr_task[v][3],
                    "id_stasiun": curr_task[v][4],
                    "nama_stasiun": curr_task[v][5]}
                    for v in range(len(curr_task))]
        
        list_stasiun = select_query("""
            SELECT *
            FROM STASIUN;
            """)

        list_stasiun = [{"id_stasiun": v[0],
                        "nama": v[4]}
                        for v in list_stasiun]

        list_petugas = select_query("""
            SELECT pt.ktp, ps.nama
            FROM PETUGAS pt, PERSON ps
            WHERE pt.ktp = ps.ktp;
            """)

        list_petugas = [{"no_ktp": v[0],
                        "nama_petugas": v[1]}
                        for v in list_petugas]

        data = {
            "task" : curr_task[0],
            "account_name": request.COOKIES.get('username'),
            "role" : request.COOKIES.get('role'),
            "stasiun" : list_stasiun,
            "petugas" : list_petugas
        }
    elif(request.method == 'POST'):
        # TODO: implement query
        no_ktp = request.POST.get("petugas")
        tanggal_mulai = request.POST.get("tanggal_mulai")
        tanggal_selesai = request.POST.get("tanggal_selesai")
        stasiun = request.POST.get("stasiun")

        rows_updated_to_acara = insert_update_delete_query("""
            UPDATE PENUGASAN
            SET ktp = '%s', start_datetime = '%s', end_datetime = '%s', id_stasiun = '%s'
            WHERE ktp = '%s' AND start_datetime = '%s' AND id_stasiun = '%s';
            """ % (no_ktp, tanggal_mulai, tanggal_selesai, stasiun, ktp, tgl_mulai, id_stasiun))
        
        return redirect('/tasks/')
    return render(request, 'update-tasks.html', data)

@csrf_exempt
def delete(request, ktp, tgl_mulai, id_stasiun):
    rows_deleted_to_acara_stasiun = insert_update_delete_query("""
        DELETE FROM PENUGASAN
        WHERE ktp = '%s' AND start_datetime = '%s' AND id_stasiun = '%s';
        """ % (ktp, tgl_mulai, id_stasiun))
    return redirect('/tasks/')

a2_cud_tasks/templates/create-tasks.html
{% extends "html_base.html" %}
{% load staticfiles %}


{% block title %}ShareBike{% endblock %}


{% block local_static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}


{% block body %}
    {% if role == "admin" %}
        <div class="container">
                <form action="{% url 'task:create' %}" method="POST">
                    <div class="form-group">
                        <label for="petugas"><b>Petugas</b></label>
                        <select class="form-control" id="petugas" name="petugas" required>
                            {% for p in petugas %}
                            <option value="{{ p.no_ktp }}">{{ p.nama_petugas }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                            <label for="tanggal_mulai"><b>Tanggal Mulai</b></label>
                            <input type="date" name="tanggal_mulai" class="form-control" id="tanggal_mulai" required>
                        </div>
                        <div class="form-group">
                            <label for="tanggal_selesai"><b>Tanggal Selesai</b></label>
                            <input type="date" name="tanggal_selesai" class="form-control" id="tanggal_selesai" required>
                        </div>
                    <div class="form-group">
                        <label for="stasiun"><b>Stasiun</b></label>
                        <select class="form-control" id="stasiun" name="stasiun" required>
                            {% for s in stasiun %}
                            <option value="{{ s.id_stasiun }}">{{ s.nama }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Create task!</button>
                </form>
        </div>
    {% endif %}

    {% if role == "anggota" or role == "petugas" %}
        <div>You are not Authorized to access this page.</div>
    {% endif %}
	<footer class="container-fluid text-center">
		<p>2019, ShareBike team.</p> 
	</footer>
{% endblock %}

a2_cud_tasks/templates/index-tasks.html
{% extends "html_base.html" %}
{% load staticfiles %}


{% block title %}ShareBike{% endblock %}


{% block local_static %}
 <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block body %}
 <div class="container">
  {% if role == "admin" %}
   <div clas="row">
    <a href="{% url 'task:create' %}"><button type="button" class="btn btn-success">Create Task</button></a>
   </div>
  {% endif %}
  <div class="row">
   <table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
     <tr>
      <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="id
      : activate to sort column ascending">No
      </th>
      <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="petugas
      : activate to sort column ascending">Petugas
      </th>
      <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="tanggal_mulai
      : activate to sort column ascending">Tanggal Mulai
      </th>
      <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="tanggal_selesai
      : activate to sort column ascending">Tanggal Akhir
      </th>
      <th class="th-sm sorting" tabindex="0" aria-controls="dtBasicExample" rowspan="1" colspan="1" aria-label="stasiun
      : activate to sort column ascending">Stasiun
      </th>
      {% if role == "admin" %}
        <th class="th-sm">ACTION
        </th>
        {% endif %}
     </tr>
    </thead>
    <tbody>
     {% for task in tasks %}
     <tr>
      <td>{{ task.id_task }}</td>
      <td>{{ task.no_ktp }} - {{ task.nama_petugas }}</td>
      <td>{{ task.tanggal_mulai|date:"j F Y" }}</td>
      <td>{{ task.tanggal_selesai|date:"j F Y" }}</td>
      <td>{{ task.id_stasiun }} - {{ task.nama_stasiun }}</td>
      {% if role == "admin" %}
      <td>
        <a href="{% url 'task:update' ktp=task.no_ktp tgl_mulai=task.tanggal_mulai id_stasiun=task.id_stasiun %}"><button type="button" class="btn btn-primary">Update</button></a>
        <a href="{% url 'task:delete' ktp=task.no_ktp tgl_mulai=task.tanggal_mulai id_stasiun=task.id_stasiun %}"><button type="button" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?');">Delete</button></a>
     </td>
     {% endif %}
     </tr>
     {% endfor %}
    </tbody>
   </table>
  </div>
 </div>

 <footer class="container-fluid text-center">
  <p>2019, ShareBike team.</p> 
 </footer>
 <script>
    $(document).ready(function() {
     $('#dtBasicExample').DataTable();
     });
  </script>
{% endblock %}

a2_cud_tasks/templates/update-tasks.html
{% extends "html_base.html" %}
{% load staticfiles %}


{% block title %}ShareBike{% endblock %}


{% block local_static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}


{% block body %}
    {% if role == "admin" %}
        <div class="container">
                <form action="{% url 'task:update' ktp=task.no_ktp tgl_mulai=task.tanggal_mulai id_stasiun=task.id_stasiun %}" method="POST">
                    <div class="form-group">
                        <label for="petugas"><b>Petugas</b></label>
                        <select class="form-control" id="petugas" name="petugas" required>
                            {% for p in petugas %}
                            {% if p.no_ktp == task.no_ktp %}
                            <option value="{{ p.no_ktp }}" selected="selected">{{ p.nama_petugas }}</option>
                            {% else %}
                            <option value="{{ p.no_ktp }}">{{ p.nama_petugas }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                            <label for="tanggal_mulai"><b>Tanggal Mulai</b></label>
                            <input type="date" name="tanggal_mulai" class="form-control" id="tanggal_mulai" value="{{ task.tanggal_mulai|date:'Y-m-d' }}" required>
                        </div>
                        <div class="form-group">
                            <label for="tanggal_selesai"><b>Tanggal Selesai</b></label>
                            <input type="date" name="tanggal_selesai" class="form-control" id="tanggal_selesai" value="{{ task.tanggal_selesai|date:'Y-m-d' }}" required>
                        </div>
                    <div class="form-group">
                        <label for="stasiun"><b>Stasiun</b></label>
                        <select class="form-control" id="stasiun" name="stasiun" required>
                            {% for s in stasiun %}
                            {% if s.id_stasiun == task.id_stasiun %}
                            <option value="{{ s.id_stasiun }}" selected="selected">{{ s.nama }}</option>
                            {% else %}
                            <option value="{{ s.id_stasiun }}">{{ s.nama }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
        </div>
    {% endif %}

    {% if role == "anggota" or role == "petugas" %}
        <div>You are not Authorized to access this page.</div>
    {% endif %}
	<footer class="container-fluid text-center">
		<p>2019, ShareBike team.</p> 
	</footer>
{% endblock %}