BikeSharing/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('a0_landing_page.urls')),
    path('admin/', admin.site.urls),

    # A1
    path('login', include('a1_login.urls')),
    path('register', include('a1_register.urls')),
    path('topup', include('a1_top_up.urls')),

    # A2
    path('tasks/', include('a2_cud_tasks.urls')),
    path('events/', include('a2_cud_events.urls')),

    # A3
    path('bikes/', include('a3_view_bikes.urls')),
    path('stations/', include('a3_view_stations.urls')),

    # A4
    path('voucher/', include('a4_cud_vouchers.urls')),
    path('rents/', include('a4_cu_rents.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

a1_login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
]

a3_view_stations/urls.py
from django.urls import path

from . import views

app_name = 'stations'
urlpatterns = [
    path('', views.index, name='stations-index'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete')
]

a3_view_stations/models.py
from django.db import models

# Create your models here.

a3_view_stations/views.py
from django.shortcuts import render


def index(request):
    context = {
        "account_name": "Akhmad Ramadhan Yamin",
        "role": "admin",
        "stations": [
            {
                "name": "Stasiun Jalan Kenanga",
                "coord": "-3.14159285, 115.213134",
                "addr": "Jl. Temen Oblak, Paraguay, Lorem ipsum dolor sit amet.",
                "bike_amt": 9,
            },
            {
                "name": "Stasiun Jalan Salam",
                "coord": "-3.177013, 115.000000",
                "addr": "Jl. Waloyo Yamoni, Kab. Baba Yetu, Lorem ipsum dolor sit amet.",
                "bike_amt": 0,
            },
            {
                "name": "Stasiun Jalan Agathis",
                "coord": "-3.14159285, 115.213134",
                "addr": "Mt. Vinson Massif, Antarctica, Lorem ipsum dolor sit amet.",
                "bike_amt": 9,
            },
            {
                "name": "Stasiun Ada Aja",
                "coord": "-3.14159285, 115.213134",
                "addr": "Mt. Vinson Massif, Antarctica, Lorem ipsum dolor sit amet.",
                "bike_amt": 9,
            },
        ],
    }
    return render(request, 'view_stations/view_stations.html', context)

def update(request):
    data ={}
    if(request.method == 'GET'):
        data = {
            "account_name": "Akhmad Ramadhan Yamin",
            "role": "admin",
            "station" : {
                "name": "Stasiun Jalan Kenanga",
                "coord": "-3.14159285, 115.213134",
                "addr": "Jl. Temen Oblak, Paraguay, Lorem ipsum dolor sit amet.",
                "bike_amt": 9,
            }
        }
    elif(request.method == 'POST'):
        # TODO: implement query
        data = {
            "account_name": "Akhmad Ramadhan Yamin",
            "role": "admin",
            "station" : {
                "name": "Stasiun Jalan Kenanga",
                "coord": "-3.14159285, 115.213134",
                "addr": "Jl. Temen Oblak, Paraguay, Lorem ipsum dolor sit amet.",
                "bike_amt": 9,
            }
        }
        return redirect('/stations/')
    return render(request, 'update-stations.html', data)

def delete(request):
    data ={}
    if(request.method == 'GET'):
        data = {
            "account_name": "Akhmad Ramadhan Yamin",
            "role": "admin",
            "station" : {
                "name": "Stasiun Jalan Kenanga",
                "coord": "-3.14159285, 115.213134",
                "addr": "Jl. Temen Oblak, Paraguay, Lorem ipsum dolor sit amet.",
                "bike_amt": 9,
            }
        }
    elif(request.method == 'POST'):
        # TODO: implement query
        data = {
            "account_name": "Akhmad Ramadhan Yamin",
            "role": "admin",
            "station" : {
                "name": "Stasiun Jalan Kenanga",
                "coord": "-3.14159285, 115.213134",
                "addr": "Jl. Temen Oblak, Paraguay, Lorem ipsum dolor sit amet.",
                "bike_amt": 9,
            }
        }
        return redirect('/stations/')
    return render(request, 'delete-stations.html', data)

a3_view_stations/templates/view_stations/view_stations.html
{% extends "html_base.html" %}
{% load staticfiles %}


{% block title %}ShareBike{% endblock %}


{% block local_static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block body %}
	{% if role == "anggota" or role == "admin"  %}
	<div class="container">
		<div class="m-1 p-1 mt-3"></div>
			{% for station in stations %}
				<div class="row">
					<div class="col-md-9">
						<div class="m-3 mb-5 border rounded card bg-light mb-3">
							<div class="card-header">
								<h4>{{ station.name }}</h4>
							</div>
							<div class="ml-4 row card-body">
								<div class="col-sm-7 border-right">
										<div class="row"><b>Koordinat:&nbsp</b> {{ station.coord }} </div>
                                        <div class="row"><b>Alamat:&nbsp</b> {{ station.addr }} </div>
                                        <div class="row"><b>Jumlah sepeda tersedia:&nbsp</b> {{ station.bike_amt }}  </div>
                                </div>
                                
                                <div class="col-sm-4 ml-3">
                                    {% if station.bike_amt > 0 %}
									<a href="#" class="btn btn-block btn-primary">Sewa Sepeda</a>
									{% endif %}
								
									{% if role == "admin" %}
										<a href="{%url 'stations:update' %}" class="btn btn-block btn-primary">Update</a>
										<a href="{%url 'stations:delete' %}" class="btn btn-block btn-danger">Delete</a>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
	{% endif %}
	</div>

	<footer class="container-fluid text-center">
		<p>2019, ShareBike team.</p> 
	</footer>
{% endblock %}

a3_view_stations/templates/view_stations/view_stations_old.html
{% extends "html_base.html" %}
{% load staticfiles %}


{% block title %}ShareBike{% endblock %}


{% block local_static %}
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}


{% block body %}
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span> 
				</button>
				<a class="navbar-brand" href="#">
					ShareBike
				</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#">
						{{ account_name }}
						<span class="badge">{{ account_balance }}</span>
					</a></li>
					<li><a href="#">Cari stasiun</a></li>
					<li><a href="#">Pinjaman Saya</a></li>
					<li><a href="#">ShareBike Pay</a></li>
					<li><a href="#">Logout</a></li>
				</ul>
			</div>
		</div>
	</nav>

	<br><br><br>

	<div class="container">
		<div class="row">
			<div class="col-md-9">
				{% for station in stations %}
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4>{{ station.name }}</h4>
					</div>
					<div class="panel-body">
						<small>
							<span class="glyphicon glyphicon-map-marker"></span>
							{{ station.coord }}
						</small>
						<h5>Jumlah sepeda tersedia: <b>{{ station.bike_amt }}</b></h5>
						<p>{{ station.addr }}</p>
						<a href="#" class="btn btn-block btn-primary">Update</a>
						<a href="#" class="btn btn-block btn-primary">Delete</a>
					</div>
				</div>
				{% endfor %}
			</div>

			<div class="col-md-3">
				<div class="panel">
					<div class="panel-body">
						<h2>{{ account_name }}</h2>
						<p><span class="glyphicon glyphicon-user"></span> Admin</p>
						<hr>
						<table class="table-condensed">
							<tr>
								<td>Saldo BikeShare Pay</td>
								<td>{{ account_balance }}</td>
							</tr>
							<tr>
								<td>Poin Voucher</td>
								<td>0</td>
							</tr>
						</table>
					</div>
				</div>
			</div>

		</div>
	</div>

	<footer class="container-fluid text-center">
		<p>2019, ShareBike team.</p> 
	</footer>
{% endblock %}