BikeSharing/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('a0_landing_page.urls')),
    path('admin/', admin.site.urls),

    # A1
    path('login', include('a1_login.urls')),
    path('register', include('a1_register.urls')),
    path('topup', include('a1_top_up.urls')),

    # A2
    path('tasks/', include('a2_cud_tasks.urls')),
    path('events/', include('a2_cud_events.urls')),

    # A3
    path('bikes/', include('a3_view_bikes.urls')),
    path('stations/', include('a3_view_stations.urls')),

    # A4
    path('voucher/', include('a4_cud_vouchers.urls')),
    path('rents/', include('a4_cu_rents.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

a1_login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
]

a1_register/urls.py
from django.urls import path

from . import views

app_name = 'register'
urlpatterns = [
    path('', views.index, name='index'),
]

a2_cud_events/urls.py
from django.urls import path

from . import views

app_name = 'event'
urlpatterns = [
    path('', views.index, name='events-index'),
    path('create/', views.create, name='create'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete')
]

a2_cud_tasks/urls.py
from django.urls import path

from . import views

app_name = 'task'
urlpatterns = [
    path('', views.index, name='tasks-index'),
    path('create/', views.create, name='create'),
    path('update/<str:ktp>/<str:tgl_mulai>/<str:id_stasiun>', views.update, name='update'),
    path('delete/<str:ktp>/<str:tgl_mulai>/<str:id_stasiun>', views.delete, name='delete')
]

a4_cu_rents/urls.py
from django.urls import path

from . import views

app_name = 'rents'
urlpatterns = [
    path('', views.index, name='rents-index'),
    path('update/', views.update, name='update'),
    path('create/', views.create, name='create'),
]

templates/html_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title %}ShareBike{% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

	<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
			<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
			<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	{% block local_static %}{% endblock %}
</head>

<body>
	<div class="container-fluid">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<a class="navbar-brand" href="#">Bike Sharing - {{account_name}}</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav">
						<a class="nav-item nav-link active" href="{% url 'landing_page:index' %}">Home <span class="sr-only">(current)</span></a>
						<a class="nav-item nav-link" href="{% url 'login:index' %}">Login</a>
						<a class="nav-item nav-link" href="{% url 'register:index' %}">Daftar</a>
						<a class="nav-item nav-link" href="{% url 'task:tasks-index' %}">Tasks</a>
						<a class="nav-item nav-link" href="{% url 'event:events-index' %}">Events</a>
						<a class="nav-item nav-link" href="{% url 'voucher:voucher-index' %}">Voucher</a>
						<a class="nav-item nav-link" href="{% url 'rents:rents-index' %}">Rent</a>
						<a class="nav-item nav-link" href="{% url 'stations:stations-index' %}">Stations</a>
						<a class="nav-item nav-link" href="{% url 'bikes:bikes-index' %}">Bikes</a>
						<button class="nav-item nav-link" onclick="document.cookie = 'username=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;'; document.cookie = 'no_kartu_user=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;'; document.cookie = 'role=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';">Logout</button>
					</div>
				</div>
			</nav>
			{% block body %}{% endblock %}
	</div>
		
	</body>
</html>